config_type: experiment
dataset:
  datasets:
    - name: pfdeltadata
      root_dir: /mnt/home/donti-group-shared/pfdelta_data
      case_name: case118
      split: train
      task: 1.3
      model: PFNet
      transform: pfnet_data_mean0_var1
    - name: pfdeltadata
      root_dir: /mnt/home/donti-group-shared/pfdelta_data
      case_name: case118
      split: val
      task: 1.3
      model: PFNet
      transform: pfnet_data_mean0_var1
functional:
  config: graph_moe_v21_conf_hier_task31
  run_location: runs/moe_variants/graph_moe_v21_conf_hier
  run_name: graph_moe_v21_conf_hier_seed_%seed
  seed: 42
  cpu: false
  is_debug: false
  trainer_name: gnn_trainer
model:
  name: graph_moe_v21_conf_hier
  in_dim: 6
  hidden_dim: 256
  out_dim: 6
  n_layers: 6
optim:
  optimizer:
    name: Adam
    lr: 0.0005
  train_params:
    batch_size: 64
    epochs: 100
    train_loss:
      - name: GNNTorchLoss
        torch_nn_name: MSELoss
        output_name: bus__y
      - name: pfn_masked_mse
        regularize: false
      - model: PFNet
        name: universal_power_balance
  val_params:
    batch_size: 64
    report_every: 5
    early_stop:
      decrease_by: 0.01
      decrease_for: 10
      needs_best_every: 15
    val_loss:
      - name: pfn_masked_mse
        regularize: false
      - name: GNNTorchLoss
        torch_nn_name: MSELoss
        output_name: bus__y
